### ISSUE TITLE
Conflict with Callouts

### ISSUE THREAD

**Issue by AndyLiu9** [Superschnizel/obisdian-fast-text-color#13]
With foldable callouts, once open the plugin and reopen the page, the callout can't be unfolded anymore.

```
> [!faq]- Are callouts foldable?
> Yes! In a foldable callout, the contents are hidden when the callout is collapsed.
```

![Fast color](https://github.com/Superschnizel/obisdian-fast-text-color/assets/88693956/d27cb674-4503-4dea-bb68-bb18a7e00650)

**Comment by Superschnizel** [comment]
@AndyLiu9 I created a new Version with an improved rendering method, that will hopefully deal with these issues. Because i am still unsure about the stability i would like to test it a bit further you have to enable the reworked rendering in the settings.

Please try out the new rendering and tell me if your issues are resolved.

**Comment by AndyLiu9** [comment]
Now looks solved.
