### ISSUE TITLE
[Bug] Error with codelines

### ISSUE THREAD

**Issue by Jack-Chronicle** [Superschnizel/obisdian-fast-text-color#14]
**Describe the bug**
Having a second codeline doesn't render properly, with a caret at the front rather than rendering correctly

The screenshot simply has two lines of text, each marked as code with a ` at the start and end of each line

![Code Error](https://github.com/user-attachments/assets/f1d15398-e277-455e-85db-11779b66721b)

**Comment by Superschnizel** [comment]
@Jack-Chronicle I created a new Version (1.0.7) with an improved rendering method, that will hopefully deal with these issues. Because i am still unsure about the stability i would like to test it a bit further you have to enable the reworked rendering in the settings.

Please try out the new rendering and tell me if your issues are resolved.

**Comment by Jack-Chronicle** [comment]
Not having any apparent issues now, will let you know if anything else comes up, but all the issues I was having are solved for now
