### ISSUE TITLE
[Bug] Dataview stops working

### ISSUE THREAD

**Issue by Dobby5972** [Superschnizel/obisdian-fast-text-color#17]
**Version**
1.06

**Describe the bug**
When FTC is activated notes freeze while using Dataview or get "Loading..."

**Comment by Superschnizel** [comment]
could you give me an example of a dataview query that is not working?

**Comment by Tanjamuse** [comment]
I know I'm not OP, but as far as I've discovered it's every dataview query that is affected.

**Comment by Tanjamuse** [comment]
and it doesn't matter whether it's a list or a table

**Comment by Superschnizel** [comment]
@Tanjamuse @Dobby5972 I did not face any problems when using dataview before, but i would think that it has to do with the current rendering method, that removed some interactivity from objects.

I just released version 1.0.7, which has a reworked rendering method that should preserve all interactive object. Because this method a lot more complicated than the previous one i want to test it a bit more so for now you will have to manually enable it in the settings.

Please try out the new method and let me know if it fixes your issues.

**Comment by Tanjamuse** [comment]
As far as I can tell everything works as it's supposed to now, I will let you know if anything happens, and look forward to more updates from you. Thanks for your hard work.

**Comment by Superschnizel** [comment]
That's great to hear, thanks for the kind words. I will close this issue for now.

**Comment by Tanjamuse** [comment]
If I disable the "use node rebuilding (EXPERIMENTAL)" the dataview no longer works.
