### ISSUE TITLE
[Bug] no longer working with tabs plugin

### ISSUE THREAD

**Issue by Tanjamuse** [Superschnizel/obisdian-fast-text-color#23]
Hi.

I have just updated to version 1.0.73 and it broke something in connection with the bug that's already been mentioned with the tabs plugin.

#15 

I've tried restarting Obsidian, and changing between different themes in the Fast Color Text plugin, but none of it helps.

Thank you so much in advance.

**Comment by Superschnizel** [comment]
@Tanjamuse Can you describe the problem in more detail? Does the tabs plugin not work properly or does colored text not work inside the tabs?

**Comment by Tanjamuse** [comment]
In the updated version, whenever I color the "heading" of a tab, all I can see is this: 
![FCT tabs](https://github.com/user-attachments/assets/f3c031d3-3fcc-49ec-88f0-6f98e55317a1)

and it doesn't matter whether it's in preview mode or read mode.

If I roll back to 1.0.7, it looks like this:

![FCT tabs 2](https://github.com/user-attachments/assets/e81a0af5-fa74-4430-a986-1397723053ed)

which is the color it is supposed to be.

**Comment by Superschnizel** [comment]
This is a tricky Problem to solve, since it involves coflicting executions of different plugins.

For now i was able to solve this in reading mode by running the postprocessor twice, once in the beginning (to handle icon shortcodes) and once later to handle the text generated by the tabs plugin.

The problem here is that the text from the tabs plugin is technically inside a codeblock so color will not be applied to it.

A potential solution for this would be to add a toggle in the settings (or frontmatter?) to allow the rendering of color in codeblocks. Would this be a solution you would be happy with?

**Comment by Tanjamuse** [comment]
Like adding a css-class?

Also, if it is too much of a problem, then I'll just use the HTML code for colored tabs, because after the enabling of decorations, that now works.

**Comment by Superschnizel** [comment]
@Tanjamuse,
Yeah, for now that might be the best way to do this, it seems that this is just a limitation of how these two plugins interact.

Thinking about it i generally dont think its a good idea to have Color rendered inside Codeblocks so i dont think i will implement a way to allow that.

Will close this issue for now
